///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Add_Entry recording.
    /// </summary>
    [TestModule("d8e80894-1da9-4287-8eb1-aee06654c411", ModuleType.Recording, 1)]
    public partial class Add_Entry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static Add_Entry instance = new Add_Entry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Add_Entry()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Add_Entry Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.TestDatabase' at 30;12.", repo.RxMainFrame.TestDatabaseInfo, new RecordItemIndex(0));
            repo.RxMainFrame.TestDatabase.Click("30;12");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.FirstName' at 49;3.", repo.RxMainFrame.RxTabStandard.FirstNameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard.FirstName.Click("49;3");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Serdar' with focus on 'RxMainFrame.RxTabStandard.FirstName'.", repo.RxMainFrame.RxTabStandard.FirstNameInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabStandard.FirstName.PressKeys("Serdar");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.LastName' at 30;0.", repo.RxMainFrame.RxTabStandard.LastNameInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabStandard.LastName.Click("30;0");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Yildiz' with focus on 'RxMainFrame.RxTabStandard.LastName'.", repo.RxMainFrame.RxTabStandard.LastNameInfo, new RecordItemIndex(4));
            repo.RxMainFrame.RxTabStandard.LastName.PressKeys("Yildiz");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.Text1001' at 156;4.", repo.RxMainFrame.RxTabStandard.Text1001Info, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabStandard.Text1001.Click("156;4");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.Open' at 9;15.", repo.RxMainFrame.RxTabStandard.OpenInfo, new RecordItemIndex(6));
            repo.RxMainFrame.RxTabStandard.Open.Click("9;15");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Development' at 281;6.", repo.List1000.DevelopmentInfo, new RecordItemIndex(7));
            repo.List1000.Development.Click("281;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'RxMainFrame.RxTabStandard.UpDownEdit' at 97;2.", repo.RxMainFrame.RxTabStandard.UpDownEditInfo, new RecordItemIndex(8));
            repo.RxMainFrame.RxTabStandard.UpDownEdit.DoubleClick("97;2");
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '25' on item 'RxMainFrame.RxTabStandard.UpDownEdit'.", repo.RxMainFrame.RxTabStandard.UpDownEditInfo, new RecordItemIndex(9));
            repo.RxMainFrame.RxTabStandard.UpDownEdit.Element.SetAttributeValue("Text", "25");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.RdbMale' at 4;15.", repo.RxMainFrame.RxTabStandard.RdbMaleInfo, new RecordItemIndex(10));
            repo.RxMainFrame.RxTabStandard.RdbMale.Click("4;15");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.BtnAddPerson' at 52;11.", repo.RxMainFrame.BtnAddPersonInfo, new RecordItemIndex(11));
            repo.RxMainFrame.BtnAddPerson.Click("52;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.LblNumberOfPersonsNumber' at 3;3.", repo.RxMainFrame.RxTabStandard.LblNumberOfPersonsNumberInfo, new RecordItemIndex(12));
            repo.RxMainFrame.RxTabStandard.LblNumberOfPersonsNumber.Click("3;3");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1') on item 'RxMainFrame.RxTabStandard.LblNumberOfPersonsNumber'.", repo.RxMainFrame.RxTabStandard.LblNumberOfPersonsNumberInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.RxMainFrame.RxTabStandard.LblNumberOfPersonsNumberInfo, "Text", "1");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
