///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("db4c1ce0-d72b-455c-894f-1859087756a1")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        MyTestRepositoryFolders.List1000AppFolder _list1000;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("db4c1ce0-d72b-455c-894f-1859087756a1")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "db4c1ce0-d72b-455c-894f-1859087756a1", ".\\RepositoryImages\\MyTestRepositorydb4c1ce0.rximgres")
        {
            _rxmainframe = new MyTestRepositoryFolders.RxMainFrameAppFolder(this);
            _list1000 = new MyTestRepositoryFolders.List1000AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("db4c1ce0-d72b-455c-894f-1859087756a1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("7f8ddf8f-56cc-4706-a23f-8bc8c880d39b")]
        public virtual MyTestRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("441a9117-c410-4ba9-8021-476607d6d4a5")]
        public virtual MyTestRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("7f8ddf8f-56cc-4706-a23f-8bc8c880d39b")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            MyTestRepositoryFolders.RxTabStandardFolder _rxtabstandard;
            RepoItemInfo _testdatabaseInfo;
            RepoItemInfo _btnaddpersonInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "7f8ddf8f-56cc-4706-a23f-8bc8c880d39b", "")
            {
                _rxtabstandard = new MyTestRepositoryFolders.RxTabStandardFolder(this);
                _testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "?/?/tabpage[@accessiblename='Test database']", "", 30000, null, "a0e863a0-f87f-4138-8550-d14401c2d8ff");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "?/?/tabpage[@controlname='RxTabStandard']/button[@controlname='btnAddPerson']", "", 30000, null, "a664b031-aec6-4d48-8258-be3321bdeecc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7f8ddf8f-56cc-4706-a23f-8bc8c880d39b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7f8ddf8f-56cc-4706-a23f-8bc8c880d39b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TestDatabase item.
            /// </summary>
            [RepositoryItem("a0e863a0-f87f-4138-8550-d14401c2d8ff")]
            public virtual Ranorex.TabPage TestDatabase
            {
                get
                {
                    return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase item info.
            /// </summary>
            [RepositoryItemInfo("a0e863a0-f87f-4138-8550-d14401c2d8ff")]
            public virtual RepoItemInfo TestDatabaseInfo
            {
                get
                {
                    return _testdatabaseInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("a664b031-aec6-4d48-8258-be3321bdeecc")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("a664b031-aec6-4d48-8258-be3321bdeecc")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The RxTabStandard folder.
            /// </summary>
            [RepositoryFolder("c3fc2d9d-f935-4d2d-b608-b168cac22cc7")]
            public virtual MyTestRepositoryFolders.RxTabStandardFolder RxTabStandard
            {
                get { return _rxtabstandard; }
            }
        }

        /// <summary>
        /// The RxTabStandardFolder folder.
        /// </summary>
        [RepositoryFolder("c3fc2d9d-f935-4d2d-b608-b168cac22cc7")]
        public partial class RxTabStandardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openInfo;
            RepoItemInfo _rdbmaleInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _text1001Info;
            RepoItemInfo _updowneditInfo;
            RepoItemInfo _lblnumberofpersonsnumberInfo;
            RepoItemInfo _serdaryildizmale25developmentInfo;
            RepoItemInfo _rxtabstandardInfo;

            /// <summary>
            /// Creates a new RxTabStandard  folder.
            /// </summary>
            public RxTabStandardFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "c3fc2d9d-f935-4d2d-b608-b168cac22cc7", "")
            {
                _openInfo = new RepoItemInfo(this, "Open", "?/?/button[@accessiblename='Open']", "", 30000, null, "725c3ea8-7e45-4b3f-8160-528723f43c97");
                _rdbmaleInfo = new RepoItemInfo(this, "RdbMale", "?/?/radiobutton[@controlname='rdbMale']", "", 30000, null, "ca54cbc1-ebee-4939-9dea-71ed0586fdab");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", "", 30000, null, "8a8ac345-70b9-4c86-b9a5-1fbe65879f4d");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", "", 30000, null, "df33ef90-82de-4418-8d28-f0fb3a739308");
                _text1001Info = new RepoItemInfo(this, "Text1001", "?/?/text[@controlid='1001']", "", 30000, null, "7a0e96eb-8202-4785-9fd3-60d58983beeb");
                _updowneditInfo = new RepoItemInfo(this, "UpDownEdit", "?/?/text[@controlname='upDownEdit']", "", 30000, null, "70ea34cd-e0c9-4594-8562-a97801b83db2");
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", "text[@controlname='lblNumberOfPersonsNumber']", "", 30000, null, "37c4d463-d8d5-4e71-a7ff-7742dd06bab8");
                _serdaryildizmale25developmentInfo = new RepoItemInfo(this, "SerdarYildizMale25Development", "list[@controlname='lstPersonList']/?/?/listitem[@accessiblename>'Serdar Yildiz (male, 25)']", "", 30000, null, "492b3030-096e-4819-92bb-dc48a17cc1b5");
                _rxtabstandardInfo = new RepoItemInfo(this, "RxTabStandard", "", "", 30000, null, "73f68f7b-286c-49f6-adb6-b507bb72a318");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c3fc2d9d-f935-4d2d-b608-b168cac22cc7")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c3fc2d9d-f935-4d2d-b608-b168cac22cc7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("725c3ea8-7e45-4b3f-8160-528723f43c97")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("725c3ea8-7e45-4b3f-8160-528723f43c97")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The RdbMale item.
            /// </summary>
            [RepositoryItem("ca54cbc1-ebee-4939-9dea-71ed0586fdab")]
            public virtual Ranorex.RadioButton RdbMale
            {
                get
                {
                    return _rdbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbMale item info.
            /// </summary>
            [RepositoryItemInfo("ca54cbc1-ebee-4939-9dea-71ed0586fdab")]
            public virtual RepoItemInfo RdbMaleInfo
            {
                get
                {
                    return _rdbmaleInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("8a8ac345-70b9-4c86-b9a5-1fbe65879f4d")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("8a8ac345-70b9-4c86-b9a5-1fbe65879f4d")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("df33ef90-82de-4418-8d28-f0fb3a739308")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("df33ef90-82de-4418-8d28-f0fb3a739308")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Text1001 item.
            /// </summary>
            [RepositoryItem("7a0e96eb-8202-4785-9fd3-60d58983beeb")]
            public virtual Ranorex.Text Text1001
            {
                get
                {
                    return _text1001Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1001 item info.
            /// </summary>
            [RepositoryItemInfo("7a0e96eb-8202-4785-9fd3-60d58983beeb")]
            public virtual RepoItemInfo Text1001Info
            {
                get
                {
                    return _text1001Info;
                }
            }

            /// <summary>
            /// The UpDownEdit item.
            /// </summary>
            [RepositoryItem("70ea34cd-e0c9-4594-8562-a97801b83db2")]
            public virtual Ranorex.Text UpDownEdit
            {
                get
                {
                    return _updowneditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UpDownEdit item info.
            /// </summary>
            [RepositoryItemInfo("70ea34cd-e0c9-4594-8562-a97801b83db2")]
            public virtual RepoItemInfo UpDownEditInfo
            {
                get
                {
                    return _updowneditInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("37c4d463-d8d5-4e71-a7ff-7742dd06bab8")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("37c4d463-d8d5-4e71-a7ff-7742dd06bab8")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }

            /// <summary>
            /// The SerdarYildizMale25Development item.
            /// </summary>
            [RepositoryItem("492b3030-096e-4819-92bb-dc48a17cc1b5")]
            public virtual Ranorex.ListItem SerdarYildizMale25Development
            {
                get
                {
                    return _serdaryildizmale25developmentInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SerdarYildizMale25Development item info.
            /// </summary>
            [RepositoryItemInfo("492b3030-096e-4819-92bb-dc48a17cc1b5")]
            public virtual RepoItemInfo SerdarYildizMale25DevelopmentInfo
            {
                get
                {
                    return _serdaryildizmale25developmentInfo;
                }
            }

            /// <summary>
            /// The RxTabStandard item.
            /// </summary>
            [RepositoryItem("73f68f7b-286c-49f6-adb6-b507bb72a318")]
            public virtual Ranorex.TabPage RxTabStandard
            {
                get
                {
                    return _rxtabstandardInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The RxTabStandard item info.
            /// </summary>
            [RepositoryItemInfo("73f68f7b-286c-49f6-adb6-b507bb72a318")]
            public virtual RepoItemInfo RxTabStandardInfo
            {
                get
                {
                    return _rxtabstandardInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("441a9117-c410-4ba9-8021-476607d6d4a5")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _developmentInfo;
            RepoItemInfo _managementInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "441a9117-c410-4ba9-8021-476607d6d4a5", "")
            {
                _developmentInfo = new RepoItemInfo(this, "Development", "listitem[@text='Development']", "", 30000, null, "e19f1ff8-39ec-4530-a9bf-312072e86024");
                _managementInfo = new RepoItemInfo(this, "Management", "listitem[@text='Management']", "", 30000, null, "d2ea8ecb-20b1-41ca-8bbf-85abb04d46f1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("441a9117-c410-4ba9-8021-476607d6d4a5")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("441a9117-c410-4ba9-8021-476607d6d4a5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Development item.
            /// </summary>
            [RepositoryItem("e19f1ff8-39ec-4530-a9bf-312072e86024")]
            public virtual Ranorex.ListItem Development
            {
                get
                {
                    return _developmentInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Development item info.
            /// </summary>
            [RepositoryItemInfo("e19f1ff8-39ec-4530-a9bf-312072e86024")]
            public virtual RepoItemInfo DevelopmentInfo
            {
                get
                {
                    return _developmentInfo;
                }
            }

            /// <summary>
            /// The Management item.
            /// </summary>
            [RepositoryItem("d2ea8ecb-20b1-41ca-8bbf-85abb04d46f1")]
            public virtual Ranorex.ListItem Management
            {
                get
                {
                    return _managementInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Management item info.
            /// </summary>
            [RepositoryItemInfo("d2ea8ecb-20b1-41ca-8bbf-85abb04d46f1")]
            public virtual RepoItemInfo ManagementInfo
            {
                get
                {
                    return _managementInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
